spring:
  application:
    name: zuppay-rest
  jpa:
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgresql
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/zuppay}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWD:postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
